### ISSUE TITLE
Chinese-Mixtral-Instruct有考虑上传到魔塔社区吗？

### ISSUE THREAD

**Issue by xujunrt** [ymcui/Chinese-Mixtral#12]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-Mixtral/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-Mixtral/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

None

### 操作系统

None

### 详细描述问题

百度和HF这两种方式下载都非常慢，对linux系统支持不友好。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（图片请放在代码块外，否则不能显示）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（图片请放在代码块外，否则不能显示）
```

**Comment by ymcui** [comment]
暂时没有精力做更多分流。
1）HF本身就支持CLI方式下载，搭配hf_transfer速度还是很可观的。
2）试过https://hf-mirror.com没有？
