### ISSUE TITLE
训练脚本会开放吗

### ISSUE THREAD

**Issue by wanghao-007** [ymcui/Chinese-Mixtral#13]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-Mixtral/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-Mixtral/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 操作系统

Linux

### 详细描述问题

在此处粘贴运行代码
```
none

### 依赖情况（代码类问题务必提供）


non

### 运行日志或截图


none

**Comment by iMountTai** [comment]
本仓库开源的chinese-mixtral与英文mixtral在结构、词表等方面没有差异，所有支持英文mixtral训练、推理的代码均适用，因此未开源相应训练脚本。你也可以参考[Chinese-LLaMA-Alpaca-2](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2)的训练脚本修改对应参数以支持mixtral训练。

**Comment by cooper12121** [comment]
> 本仓库开源的chinese-mixtral与英文mixtral在结构、词表等方面没有差异，所有支持英文mixtral训练、推理的代码均适用，因此未开源相应训练脚本。你也可以参考[Chinese-LLaMA-Alpaca-2](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2)的训练脚本修改对应参数以支持mixtral训练。

请问在使用alpaca指令数据时，指令模板是怎么设计的

**Comment by Mxianying** [comment]
> 本仓库开源的chinese-mixtral与英文mixtral在结构、词表等方面没有差异，所有支持英文mixtral训练、推理的代码均适用，因此未开源相应训练脚本。你也可以参考[Chinese-LLaMA-Alpaca-2](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2)的训练脚本修改对应参数以支持mixtral训练。

可是仅供调试，会开放实际的sft参数吗

**Comment by cooper12121** [comment]
> > 本仓库开源的chinese-mixtral与英文mixtral在结构、词表等方面没有差异，所有支持英文mixtral训练、推理的代码均适用，因此未开源相应训练脚本。你也可以参考[Chinese-LLaMA-Alpaca-2](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2)的训练脚本修改对应参数以支持mixtral训练。
> 
> 可是仅供调试，会开放实际的sft参数吗

谢谢你的回复。其实训练脚本这些都没有什么区别，但目前我在微调mixtral-8*7b时遇到了一些问题，以下均是基于lora微调
1 使用deepspeed zero3报错weight 2-D,或者卡住。
使用zero2-no-offload抱显存，
只有4bit量化加zero2-no-offload 可以正常微调，8bit都不行。全参微调同。（在手机上编辑回复，排版请见谅）

**Comment by cooper12121** [comment]
> > 本仓库开源的chinese-mixtral与英文mixtral在结构、词表等方面没有差异，所有支持英文mixtral训练、推理的代码均适用，因此未开源相应训练脚本。你也可以参考[Chinese-LLaMA-Alpaca-2](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2)的训练脚本修改对应参数以支持mixtral训练。
> 
> 可是仅供调试，会开放实际的sft参数吗

我遇到的问题同https://github.com/hiyouga/LLaMA-Factory/issues/1998，请问你们在训练过程中有遇到过吗，怎么解决的？谢谢
