### ISSUE TITLE
训练成本问题请教？

### ISSUE THREAD

**Issue by RebornForPower** [ymcui/Chinese-Mixtral#9]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-Mixtral/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-Mixtral/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 操作系统

Linux

### 详细描述问题

（请在此处详细描述遇到的问题）
请问使用的训练数据集大小以及使用的显卡型号数量和显存情况？我们希望能够在自己的数据集上进一步的微调以适应我们自己的领域。感谢支持~

### 依赖情况（代码类问题务必提供）

不涉及

### 运行日志或截图

不涉及

**Comment by ymcui** [comment]
1. 训练数据量README里有写，20G预训练，500万条SFT：https://github.com/ymcui/Chinese-Mixtral?tab=readme-ov-file#训练与精调
2. 显卡使用的是A40-48G，数量当然是越多越快，建议你们先在单卡上评估训练速度，然后再估算训练时长。
3. 训练使用的是QLoRA，目前我们还没整理训练代码，你们可以用其他支持Mixtral的大模型微调框架。

**Comment by RebornForPower** [comment]
好的，感谢解惑，期待您的训练代码，也期待该项目越做越好~
